language: minimal

# install Hugo
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.69.2/hugo_0.69.2_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

# build the website
script:
  - hugo
  - echo 'juliagpu.org' > public/CNAME

# deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
