baseURL: https://juliagpu.github.io/juliagpu.org/
languageCode: en-us
title: JuliaGPU
theme: vanilla-bootstrap-hugo-theme
googleAnalytics: UA-154489943-1

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: Home
    pre: home
    url: /
    weight: 1
  - name: News
    pre: file-text
    url: /post/
    weight: 2
  - name: NVIDIA CUDA
    url: /nvidia/
    weight: 3
  - name: AMD ROCm
    url: /amd/
    weight: 4
  - name: OpenCL
    url: /opencl/
    weight: 5

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 700px
  dateFormat: Jan 2, 2006
  footerText: Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)
  hideFooter: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
