baseURL = "//juliagpu.org/"
languageCode = "en-us"
title = "JuliaGPU"
theme = "vanilla-bootstrap"
googleAnalytics = "UA-154489943-1"
enableGitInfo = true

[taxonomies]
tag = "tags"

[permalinks]
post = "/:filename/"

[frontmatter]
date  = [":filename"]

# See https://feathericons.com/
# The value of pre is the icon name
[menu]

  [[menu.nav]]
  name = "Home"
  pre = "home"
  url = "/"
  weight = 1

  [[menu.nav]]
  name = "Blog"
  pre = "file-text"
  url = "/post/"
  weight = 2

  [[menu.nav]]
  name = "Learn"
  pre = "book-open"
  url = "/learn/"
  weight = 3

  [[menu.nav]]
  name = "NVIDIA CUDA"
  url = "/cuda/"
  weight = 4

  [[menu.nav]]
  name = "AMD ROCm"
  url = "/rocm/"
  weight = 5

  [[menu.nav]]
  name = "OpenCL"
  url = "/opencl/"
  weight = 6

[params]
includeBootstrapJs = false
showActiveNav = true
containerMaxWidth = "700px"
dateFormat = "Jan 2, 2006"
subtitle = "High-performance GPU programming in a high-level language."
logo = "/logo_crop.png"
footerText = "Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)"
hideFooter = false

[markup]
defaultMarkdownHandler = "goldmark"

  [markup.goldmark]

    [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true

    [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true

    [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false

  [markup.highlight]
  codeFences = true
  hl_Lines = ""
  lineNoStart = 1.0
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4.0

  [markup.tableOfContents]
  endLevel = 6.0
  startLevel = 2.0
